function redraw()
  screen.clear()
  screen.level(15)
  screen.move(64,32)
  screen.text_center("delete cc2 via maiden")
  screen.move(64,40)
  screen.text_center('and re-install a fresh copy')
  screen.move(64,48)
  screen.text_center('(no data will be lost)')
  screen.update()
end